
learner         :       AGEM
optim           :       SGD
learning_rate   :       0.1
momentum        :       0
weight_decay    :       0.0001
dataset         :       cifar10
n_tasks         :       5
mem_size        :       500
mem_batch_size  :       64
batch_size      :       10
nf              :       64
training_type   :       blurry
blurry_scale    :       1500
