
learner         :       DVC
optim           :       SGD
learning_rate   :       0.1
momentum        :       0.9
weight_decay    :       0
dataset         :       cifar100
n_tasks         :       10
mem_size        :       2000
mem_batch_size  :       64
batch_size      :       10
nf              :       64
training_type   :       inc
# dl_weight is setup in DVC class directly with values from paper
