
learner         :       ERACE
optim           :       SGD
learning_rate   :       0.001
momentum        :       0.9
weight_decay    :       0
dataset         :       cifar100
n_tasks         :       10
mem_size        :       5000
mem_batch_size  :       64
batch_size      :       10
nf              :       64
training_type   :       blurry
blurry_scale    :       1500
tf_type         :       partial
