
learner         :       OCM
dataset         :       cifar10
n_tasks         :       5
mem_size        :       200
mem_batch_size  :       64
batch_size      :       10
proj_dim        :       128
nf              :       64
supervised      :       True
training_type   :       blurry
blurry_scale    :       1500
