
learner         :       OCM
dataset         :       cifar100
n_tasks         :       10
mem_size        :       1000
mem_batch_size  :       64
batch_size      :       10
proj_dim        :       128
nf              :       64
supervised      :       True
