
learner         :       OCM
dataset         :       tiny
n_tasks         :       100
mem_size        :       5000
mem_batch_size  :       64
batch_size      :       10
proj_dim        :       128
nf              :       64
supervised      :       True
