
learner         :       SCR
optim           :       SGD
learning_rate   :       0.01
momentum        :       0.9
weight_decay    :       0.0001
temperature     :       0.07
dataset         :       cifar10
n_tasks         :       5
mem_size        :       200
mem_batch_size  :       64
batch_size      :       10
proj_dim        :       128
nf              :       64
training_type   :       blurry
blurry_scale    :       1500
